language: node_js
dist: trusty # Ubuntu 14.04
before_script:
  - npm i -g bower
  - bower install

  # set up xvfb to run GUI tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_deploy:
  - npm i -g gulp
  - gulp build
deploy:
  provider: surge
  project: dist/prod
  cleanup: false
