language: node_js
dist: trusty # Ubuntu 14.04
before_script:
  - npm i -g -q bower
  - bower install -q

  # set up xvfb to run GUI tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: node --harmony_sloppy_let --harmony_destructuring $(npm bin)/karma start --single-run
before_deploy:
  - npm i -g -q gulp
  - gulp build
deploy:
  provider: surge
  project: dist/prod
  domain: https://world-power-stations.surge.sh
  cleanup: false
