language: node_js
dist: trusty # Ubuntu 14.04
before_script:
  - npm i -g -q bower
  - bower install -q

  # set up xvfb to run GUI tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
deploy:
  edge: true
  provider: surge
  domain: https://world-power-stations.surge.sh
  project: dist/prod/
